{
  "props": [],
  "components": {
    "shutdown": {
      "type": "script\\TimerScript",
      "x": 224.0,
      "y": 336.0,
      "props": {
        "interval": 1500,
        "repeatable": false,
        "autoStart": false
      }
    },
    "timerAlt": {
      "type": "script\\TimerScript",
      "x": 464,
      "y": 160,
      "props": {
        "interval": 1500,
        "repeatable": false,
        "autoStart": false
      }
    },
    "timer": {
      "type": "script\\TimerScript",
      "x": 192,
      "y": 48,
      "props": {
        "interval": 10,
        "repeatable": "1",
        "autoStart": false
      }
    }
  }
}